dashboard_items:
    prefix: /
    resource: "@RoommateBundle/Resources/config/routing/dashboard.yml"

cleaning:
    prefix: /cleaning
    resource: "@RoommateBundle/Resources/config/routing/cleaning.yml"

profile:
    prefix: /profile
    resource: "@RoommateBundle/Resources/config/routing/profile.yml"

contacts:
    prefix: /contacts
    resource: "@RoommateBundle/Resources/config/routing/contact.yml"

events:
    prefix: /events
    resource: "@RoommateBundle/Resources/config/routing/events.yml"

groceries:
    prefix: /groceries
    resource: "@RoommateBundle/Resources/config/routing/groceries.yml"

debt:
    prefix: /debt
    resource: "@RoommateBundle/Resources/config/routing/debt.yml"

authentication:
    prefix: /
    resource: "@RoommateBundle/Resources/config/routing/authentication.yml"
