dashboard_items:
    prefix: /
    resource: "@RoommateBundle/Resources/config/routing/dashboard.yml"

authentication:
    prefix: /
    resource: "@RoommateBundle/Resources/config/routing/authentication.yml"
