dashboard_items:
    prefix: /
    resource: "@RoommateBundle/Resources/config/routing/dashboard.yml"

cleaning:
    prefix: /cleaning
    resource: "@RoommateBundle/Resources/config/routing/cleaning.yml"

profile:
    prefix: /profile
    resource: "@RoommateBundle/Resources/config/routing/profile.yml"

contacts:
    prefix: /contacts
    resource: "@RoommateBundle/Resources/config/routing/contact.yml"

authentication:
    prefix: /
    resource: "@RoommateBundle/Resources/config/routing/authentication.yml"
